# Generated by Django 2.1.2 on 2018-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_final_periodo',
            field=models.DateTimeField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Fecha de finalización del período contable', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_inicio_periodo',
            field=models.DateTimeField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Fecha de inicio del nuevo período contable', null=True, verbose_name='Fecha de inicio'),
        ),
    ]
