# Generated by Django 2.1.2 on 2018-11-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20181114_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubro',
            options={'ordering': ['rubro_sup__id', 'codigo_rubro'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
    ]
