# Generated by Django 2.1.2 on 2018-11-17 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_auto_20181117_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='codigo_rubro',
            field=models.CharField(error_messages={'value': 'El código del rubro no debe ser menor a 1'}, help_text='Ingrese el código del rubro', max_length=8, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(8)], verbose_name='Código del rubro'),
        ),
    ]
