# Generated by Django 2.1.2 on 2018-11-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_auto_20181115_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='is_alta',
            field=models.BooleanField(default=True, help_text='Defina si la cuenta está en uso', verbose_name='¿Está de alta?'),
        ),
    ]
