# Generated by Django 2.1.2 on 2018-11-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_cuenta_is_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id_rubro',
            field=models.ForeignKey(help_text='Seleccion el rubro al que pertenece la cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Rubro', verbose_name='Rubro'),
        ),
    ]
