# Generated by Django 2.1.2 on 2018-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_auto_20181117_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='nombre_rubro',
            field=models.CharField(help_text='Ingrese el nombre del rubro', max_length=100, verbose_name='Nombre del rubro'),
        ),
    ]
