# Generated by Django 2.1.2 on 2018-11-18 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_auto_20181115_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='nivel',
            field=models.IntegerField(error_messages={'value': 'El nivel del rubro no debe ser menor a 1, ni mayor a 3'}, help_text='Ingrese el nivel del rubro. Ejemplo: Activo -> Es Nivel 1, Efectivo -> Es Nivel 2', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Nivel del rubro'),
        ),
    ]
