# Generated by Django 2.1.2 on 2018-11-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_rubro_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='codigo_cuenta_padre',
            field=models.ForeignKey(blank=True, help_text='Seleccione la cuenta a la que pertenece esta subcuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Cuenta', verbose_name='Cuenta Padre'),
        ),
    ]
