# Generated by Django 2.1.2 on 2018-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_auto_20181118_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='is_cuenta_acreedora',
            field=models.BooleanField(help_text='Marque este campo sí y solo sí la cuenta es de naturaleza acreedora', verbose_name='¿Es cuenta de naturaleza acreedora?'),
        ),
    ]
