# Generated by Django 2.0 on 2018-11-23 22:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_auto_20181118_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Ingrese el nombre del tipo de transacción a realizar', max_length=100, null=True, verbose_name='Nombre del tipo de transacción')),
                ('descripcion_tipo', models.CharField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Ingrese la descripción del tipo de transacción a realizar', max_length=100, null=True, verbose_name='Descripción del tipo transacción')),
            ],
            options={
                'verbose_name': 'Tipo de Transacción',
                'verbose_name_plural': 'Tipos de transacciones',
                'ordering': ['id_tipo', 'nombre_tipo'],
            },
        ),
        migrations.AlterModelOptions(
            name='periodocontable',
            options={'ordering': ['id_periodo_contable'], 'verbose_name': 'Período Contable', 'verbose_name_plural': 'Períodos Contables'},
        ),
        migrations.RenameField(
            model_name='periodocontable',
            old_name='id_perido_contable',
            new_name='id_periodo_contable',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='nombre_catalogo',
            field=models.CharField(help_text='Ingrese el nombre del catalogo', max_length=30, verbose_name='Nombre del catalogo'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='codigo_cuenta',
            field=models.IntegerField(error_messages={'value': 'Debe ser un código mayor o igual a 1'}, help_text='Debe ingresar el código de la cuenta dependiendo de su ubicación en el catálogo', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Código de la cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_alta',
            field=models.BooleanField(default=True, help_text='Marque esta casilla sí y solo sí la cuenta está en uso', verbose_name='¿Está de alta?'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_cuenta_acreedora',
            field=models.BooleanField(default=False, help_text='Marque este campo sí y solo sí la cuenta es de naturaleza acreedora', verbose_name='¿Es cuenta de naturaleza acreedora?'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre_cuenta',
            field=models.CharField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Ingrese el nombre de la cuenta', max_length=100, null=True, verbose_name='Nombre de la cuenta'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(help_text='Ingrese el nombre de la empresa', max_length=30, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_cuenta',
            field=models.ForeignKey(help_text='Seleccione una de las cuentas a afectar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Cuenta', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto_abono',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el monto a abonar (en doláres estadounidenses) a la cuenta seleccionada. <strong><br>NOTA: El monto de cumplir partida doble y ser congruente con la transacción registrada</strong>', max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser positiva')], verbose_name='Monto abono'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto_cargo',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el monto a cargar (en doláres estadounidenses) en la cuenta seleccionada.<strong><br>NOTA: El monto de cumplir partida doble y ser congruente con la transacción registrada</strong>', max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser positiva')], verbose_name='Monto cargo'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_final_periodo',
            field=models.DateTimeField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Fecha de finalización del período contable', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_inicio_periodo',
            field=models.DateTimeField(error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Fecha de inicio del nuevo período contable', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='codigo_rubro',
            field=models.CharField(error_messages={'value': 'El código del rubro no debe ser menor a 1'}, help_text='Ingrese el código del rubro', max_length=8, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(8)], verbose_name='Código del rubro'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='id_catalogo',
            field=models.ForeignKey(help_text='Seleccione el catalogo al que pertenece este rubro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Catalogo', verbose_name='Catálogo'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='nombre_rubro',
            field=models.CharField(help_text='Ingrese el nombre del rubro', max_length=100, verbose_name='Nombre del rubro'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='rubro_sup',
            field=models.ForeignKey(blank=True, help_text='Seleccione el rubro al que pertenece este subrubro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Rubro', verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_transaccion',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el monto en doláres estadounidenses de la transacción a registrar', max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser positiva')], verbose_name='Monto de la transacción'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_tipo',
            field=models.ForeignKey(help_text='Seleccione el tipo de transacción a registrar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.TipoTransaccion', verbose_name='Tipo de Transacción'),
        ),
    ]
