# Generated by Django 2.1.2 on 2018-11-18 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_auto_20181118_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='monto_abono',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el monto a abonar (en doláres estadounidenses) a la cuenta seleccionada. <br>NOTA: El monto de cumplir partida doble y ser congruente con la transacción registrada', max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser positiva')], verbose_name='Monto abono'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto_cargo',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el monto a cargar (en doláres estadounidenses) en la cuenta seleccionada. <br>NOTA: El monto de cumplir partida doble y ser congruente con la transacción registrada', max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser positiva')], verbose_name='Monto cargo'),
        ),
    ]
