# Generated by Django 2.1.2 on 2018-11-20 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_recurso',
            field=models.OneToOneField(help_text='Seleccione el recurso del producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.Recurso', verbose_name='Recurso'),
        ),
    ]
