# Generated by Django 2.1.2 on 2018-11-26 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['id_factura', 'id_proveedor'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['estado_factura', 'total_factura'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['id_factura', 'id_cliente'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_compra',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='compra',
            name='id_factura',
            field=models.ForeignKey(default=None, help_text='Seleccion la factura al que le pertenece la venta', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Factura', verbose_name='Factura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_aplicacion',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Ingrese el recargo por el impuesto a la compra o venta', max_digits=1000, validators=[django.core.validators.MinValueValidator(0, message='Este campo debe ser positivo')], verbose_name='Monto Aplicado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='id_factura',
            field=models.ForeignKey(default=None, help_text='Seleccion la factura al que le pertenece la venta', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Factura', verbose_name='Factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(help_text='Seleccion el proveedor al que le pertenece la compra', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cantidad_detalle',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese cantidad del producto o materia prima', max_digits=1000, validators=[django.core.validators.MinValueValidator(0, message='Este campo debe ser positivo')], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_factura',
            field=models.ForeignKey(help_text='Seleccione la factura que pertenece el detalle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Factura', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_materia_prima',
            field=models.ForeignKey(help_text='Seleccion la materia prima que contiene el detalle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.MateriaPrima', verbose_name='Materia Prima'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_producto',
            field=models.ForeignKey(help_text='Seleccion el producto que contiene el detalle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sub_total_factura',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el sub total antes de impuestos', max_digits=1000, validators=[django.core.validators.MinValueValidator(0, message='Este campo debe ser positivo')], verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_factura',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el total (impuestos incluídos)', max_digits=1000, validators=[django.core.validators.MinValueValidator(0, message='Este campo debe ser positivo')], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturaimpuesto',
            name='id_factura',
            field=models.ForeignKey(help_text='Seleccione la factura que se aplicara en la factura con impuesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Factura', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='facturaimpuesto',
            name='id_impuesto',
            field=models.ForeignKey(help_text='Seleccione el impuesto que se aplicara a la factura con impuesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Impuesto', verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='id_recurso',
            field=models.OneToOneField(help_text='Seleccion el recurso del que esta compuesto el kardex', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Recurso', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='id_producto',
            field=models.ForeignKey(help_text='Seleccion el producto que esta conformado por materia prima', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='id_recurso',
            field=models.OneToOneField(help_text='Seleccion el recurso para la kardex', on_delete=django.db.models.deletion.CASCADE, to='inventario.Recurso', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now=True, help_text='Ingrese en que se realizo fecha del movimiento', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_kardex',
            field=models.ForeignKey(help_text='Seleccion el kardex que posee el movimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Kardex', verbose_name='Kardex'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_recurso',
            field=models.OneToOneField(help_text='Seleccione el recurso del producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.Recurso', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='id_movimiento',
            field=models.OneToOneField(help_text='Seleccion el movimiento al que le corresponde el saldo', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Movimiento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(help_text='Seleccion el cliente al que le pertenece la venta', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Cliente', verbose_name='Cliente'),
        ),
    ]
