# Generated by Django 2.0 on 2018-11-23 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20181121_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_aplicacion',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Ingrese el recargo por el impuesto a la compra o venta', max_digits=1000, validators=[django.core.validators.MinValueValidator(0, message='Este campo debe ser positivo')], verbose_name='Monto Aplicado'),
            preserve_default=False,
        ),
    ]
