# Generated by Django 2.0 on 2018-11-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_factura_monto_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='id_proveedor',
            field=models.ForeignKey(default=None, help_text='Seleccion el proveedor al que le pertenece la compra', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.Proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
